-- CreateTable
CREATE TABLE "OAuth" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "oauth" TEXT NOT NULL,
    "dateSent" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userID" INTEGER NOT NULL,
    CONSTRAINT "OAuth_userID_fkey" FOREIGN KEY ("userID") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
